/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App3 {
    public String getGreeting() {
        return "번호: 1\n" + 
            "내용: 게시글입니다.\n" + 
            "작성일: 2019-01-01\n" + 
            "조회수: 0";
        
    }

    public static void main(String[] args) {
        System.out.println(new App2().getGreeting());
    }
}
